name: Build a pull request

on:
  workflow_call:
    inputs:
      AWS_INTEGRATION_IAM_ROLE_ARN:
        required: false
        default: ''
        type: string
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  pr:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download result artifact
        uses: actions/download-artifact@v4
        with:
          name: result-artifact
          path: tmp/myartifacts
      - name: Get the resulting filename
        run: ls -AU tmp/myartifacts | head -1
      - name: Put the artifact filename in a variable
        run: |
          TESTVAR=`ls -AU tmp/myartifacts | head -1`
          echo $TESTVAR
