name: Build a pull request

on:
  workflow_call:
    inputs:
      AWS_INTEGRATION_IAM_ROLE_ARN:
        required: false
        default: ''
        type: string
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  return:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: result-artifact
          path: /tmp/myartifacts
      - name: poof my artifact
        run: ls /tmp/myartifacts
