name: Publish release
on:
  release:
  push:
    tags:
      - '*'
  workflow_run:
    workflows:
      - 'build'
    branches:
      - 'main'
    types:
      - requested
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: ./github/workflows/build.yml
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]
    ## When build is complete, the artifact exists and can be downloaded
    # This gives an entirely new, clean, environment to use for publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: result-artifact
          path: tmp/myartifacts
      - name: poof
        run: ls tmp/myartifacts

