name: Build release
on:
  release:
  push:
    tags:
  workflow_run:
    workflows:
      - 'build'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run my awesome test
        run: echo "Hello world!"
