name: Build release
on:
  release:
  push:
    tags:
      - '*'
  workflow_run:
    workflows:
      - 'build'
    branches:
      - 'main'
    types:
      - requested
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run my awesome test
        run: echo "Hello world!"
